name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send webhook request to orchestrator
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"repository": "https://github.com/anumi1999/trial-orch", "ref": "refs/heads/main"}' \
          http://10.238.176.15:6767/webhook
